Use custom HttpClient wrapper
That logs every request before sending it, so in case of
failure it is clear exactly which request has failed.

Example of an exception that has no information about
request that has caused it:
```
error: Running program '/__w/pulumi-deploy/pulumi-deploy/BackgroundAgentsVPS/bin/Debug/net8.0/BackgroundAgentsVPS.dll' failed with an unhandled exception:
    System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
       at async Task<IDictionary<string, object>> Pulumi.Stack.RunInitAsync(Func<Task<IDictionary<string, object>>> init)
       at async Task<OutputData<T>> Pulumi.Output<T>+<>c__DisplayClass13_0.<Create>g__GetData|0(?)+GetData(?)
       at async Task<T> Pulumi.Output<T>.GetValueAsync(T whenUnknown)
       at async Task Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output<IDictionary<string, object>> outputs) ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
       at HttpResponseMessage System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
       at async Task<string> System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
       --- End of inner exception stack trace --- ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
       at HttpResponseMessage System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
       at async Task<string> System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
       --- End of inner exception stack trace ---
```