Fixed bug in Delete operation
That would cause an error:
```
unhumandomains:index:Domain (xRayDomainRecords):
    error: The given key 'domainName' was not present in the dictionary.
```

The error was caused by incorrect format of dictionary passed
to AsyncCreateOrUpdate method (needs "domainName" and "records"
properties, empty dict was passed instead).

Introduced in [1].

[1] https://github.com/nodeeffect/pulumi-unhumandomains/pull/5